title: "The Tax Refactor"
description: "A software entrepreneur's case for simple, fair, and durable U.S. tax reform."
url: "https://www.mattsly.com"
baseurl: "/fair-and-simple-tax-act"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - drafts
  - process
  - process-notes
  - internal
  - README.md
  - Makefile
  - "*.code-workspace"
  - vendor
  - Gemfile
  - Gemfile.lock
